name: Gerar Notícias Diárias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Rodar o script de geração de notícias
        env:
          HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
        run: python gerador_de_noticias.py

      - name: Fazer commit do novo site
        run: |
          git config --global user.name 'Noticias Bot'
          git config --global user.email 'action@github.com'
          git add index.html
          git diff --staged --quiet || git commit -m "📰 Atualiza notícias do dia"
          git push

